name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: pnpm install 
             pnpm install --save-dev jest

      - name: Run tests
        run: pnpm test

      - name: Commit and push changes
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

            echo "Commit SHA: $GITHUB_SHA" >> commit_info.txt  # Save commit SHA to a file
